version: "3"
services:
  db:
    build:
      context: ./mongo
      dockerfile: ./Dockerfile
    networks:
      no-internet:
        ipv4_address: 172.18.0.10
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      no-internet:
        ipv4_address: 172.18.0.11
      internet:
        ipv4_address: 172.19.0.11
    ports:
      - "8080:8080"

networks:
  no-internet:
    driver: bridge
    internal: true
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
  internet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16