version: "3"
services:
  db:
    container_name: dbhost
    build:
      context: ./mongo
      dockerfile: ./Dockerfile
    networks:
      - no-internet
  app:
    container_name: apphost
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - no-internet
      - internet
    ports:
      - "8080:8080"

networks:
  no-internet:
    driver: bridge
    internal: true
  internet:
    driver: bridge