version: "3"
services:
  db:
    container_name: dbhost
    image: krzysztofse/b2b-db
    networks:
      - no-internet
  app:
    container_name: apphost
    depends_on:
      - db
    image: krzysztofse/b2b-app
    networks:
      - no-internet
      - internet
    ports:
      - "8080:8080"

networks:
  no-internet:
    driver: bridge
    internal: true
  internet:
    driver: bridge